version: "3.9"
services:
  redis:
    image: redis:7.0.11-alpine

  app:
    container_name: container1
    build: .
    volumes:
      - .:/compose
    ports:
      - 8000:8000
    image: app:compose
    command: python manage.py runserver 0.0.0.0:8000  
    depends_on:
      - redis

  celery:
    container_name: celery
    build: .
    command: celery --app=config.celery worker -l INFO 
    volumes:
      - .:/compose
    image: app:compose
    depends_on:
      - redis
